return {
	{ "rcarriga/nvim-notify" },
	{ "williamboman/mason.nvim" },
	{ "williamboman/mason-lspconfig.nvim" },
	{ "WhoIsSethDaniel/mason-tool-installer.nvim" },
	{ "neovim/nvim-lspconfig" },
	{ "onsails/lspkind-nvim" },
	{ "hrsh7th/nvim-cmp" },
	{ "hrsh7th/cmp-nvim-lsp-signature-help" },
	{ "hrsh7th/cmp-nvim-lua",                     ft = { "lua" } },
	{ "hrsh7th/cmp-buffer" },
	{ "hrsh7th/cmp-path" },
	{ "hrsh7th/cmp-path" },
	{ "hrsh7th/cmp-nvim-lsp" },
	{ "kdheepak/cmp-latex-symbols",               lazy = true },
	{ "saadparwaiz1/cmp_luasnip" },
	{ "christoomey/vim-tmux-navigator" },
	{ "folke/neodev.nvim" },
	{ "nvim-lua/plenary.nvim" },
	{ "lukas-reineke/lsp-format.nvim" },
	{ "kyazdani42/nvim-web-devicons" },
	{ "vimwiki/vimwiki" },
	{ "junegunn/fzf" },
	{ "fladson/vim-kitty" },
	{
		"folke/todo-comments.nvim",
		dependencies = { "nvim-lua/plenary.nvim" },
		opts = {}
	},
}
