return {
	-- "nvim-telescope/telescope.nvim",
	-- cmd = { "Telescope" },
	-- keys = {
	-- 	{ "<leader>ff", "<cmd>Telescope find_files<cr>", desc = "Find Files" },
	-- 	{ "<leader>fg", "<cmd>Telescope live_grep<cr>", desc = "Grep Files" },
	-- 	{ "<leader>fb", "<cmd>Telescope buffers<cr>", desc = "Buffers" },
	-- 	{ "<leader>fh", "<cmd>Telescope help_tags<cr>", desc = "Help Tags" },
	-- 	{ "<leader>fc", "<cmd>Telescope commands<cr>", desc = "Commands" },
	-- 	{ "<leader>fs", "<cmd>Telescope lsp_document_symbols<cr>", desc = "LSP Document Symbols" },
	-- 	{ "<leader>fS", "<cmd>Telescope lsp_dynamic_workspace_symbols<cr>", desc = "LSP Dynamic Workspace Symbols" },
	-- 	{ "<leader>fr", "<cmd>Telescope lsp_references<cr>", desc = "LSP References" },
	-- 	{ "<leader>fG", "<cmd>Telescope git_files<cr>", desc = "Git Files" },
	-- 	{ "<leader>fR", "<cmd>Telescope resume<cr>", desc = "Resume Last" },
	-- },
	-- dependencies = {
	-- 	"nvim-lua/plenary.nvim",
	-- 	"piersolenski/telescope-import.nvim",
	-- },
	-- config = function()
	-- 	local actions = require("telescope.actions")

	-- 	require("telescope").setup({
	-- 		defaults = {
	-- 			prompt_prefix = "  ",
	-- 			selection_caret = "▎ ",
	-- 			multi_icon = " │ ",
	-- 			layout_strategy = "flex",
	-- 			borderchars = { "─", "│", "─", "│", "┌", "┐", "┘", "└" },
	-- 			mappings = {
	-- 				i = {
	-- 					["<C-k>"] = actions.move_selection_previous,
	-- 					["<C-j>"] = actions.move_selection_next,
	-- 					["<C-p>"] = actions.preview_scrolling_down,
	-- 					["<C-n>"] = actions.preview_scrolling_up,
	-- 				},
	-- 				n = {
	-- 					["<C-k>"] = actions.move_selection_previous,
	-- 					["<C-j>"] = actions.move_selection_next,
	-- 					["<C-p>"] = actions.preview_scrolling_down,
	-- 					["<C-n>"] = actions.preview_scrolling_up,
	-- 				},
	-- 			},
	-- 			file_ignore_patterns = {
	-- 				"node_modules",
	-- 			},
	-- 		},
	-- 		pickers = {
	-- 			buffers = {
	-- 				previewer = false,
	-- 				theme = "dropdown",
	-- 				mappings = {
	-- 					n = {
	-- 						["<C-d>"] = "delete_buffer",
	-- 						["l"] = "select_default",
	-- 					},
	-- 				},
	-- 				initial_mode = "normal",
	-- 			},
	-- 			find_files = {
	-- 				sorting_strategy = "ascending",
	-- 				previewer = true,
	-- 				find_command = { "rg", "--files", "--hidden", "--glob", "!.git/*" },
	-- 			},
	-- 			help_tags = {
	-- 				theme = "ivy",
	-- 			},
	-- 			symbols = {
	-- 				theme = "dropdown",
	-- 			},
	-- 			registers = {
	-- 				theme = "ivy",
	-- 			},
	-- 			grep_string = {
	-- 				initial_mode = "normal",
	-- 				theme = "ivy",
	-- 			},
	-- 			live_grep = {
	-- 				theme = "ivy",
	-- 			},
	-- 		},
	-- 	})
	-- end,
}
